name: mahasiswa
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.1.0
  dart_jsonwebtoken: ^2.4.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed: ^2.1.1
  freezed_annotation: ^2.1.0
  json_serializable: ^6.4.0
  path: ^1.8.2
  postgres: ^2.5.2
 
dev_dependencies:
  build_runner: ^2.2.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
